env:
  node: true
  es2021: true
  jest/globals: true
extends:
  - eslint:recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - node
  - import
  - unused-imports
  - jest
rules:
  sort-imports: 0
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
      alphabetize:
        order: asc
  '@typescript-eslint/no-unused-vars': off
  no-unused-vars: off
  unused-imports/no-unused-imports-ts: warn
