version: "3"
services:
  apollo-typescript-starter-postgresql:
    container_name: apollo-typescript-starter-postgresql
    image: postgres:11-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: "Asia/Tokyo"
      POSTGRES_DB: "graphql"
      POSTGRES_USER : "postgres"
      POSTGRES_PASSWORD : ""
      POSTGRES_INITDB_ARGS : "--encoding=UTF-8 --locale=C"
